chen_phrase_set_final: '../docs/file/chen_phrase_final/'
yang_phrase_set_final: '../docs/file/yang_phrase_final/'
total_phrase_set_final: '../docs/file/total_phrase_final/'
total_content_by_kind_dir_road: '../docs/total_content/稿件类型/'
total_content_by_industry_dir_road: '../docs/total_content/一级行业/'
total_seglist_by_kind_dir_road: '../docs/total_seglist/稿件类型/'
total_seglist_by_industry_dir_road: '../docs/total_seglist/一级行业/'
word_vec_model: '../docs/WordToVec/'
stop_words_road: '../docs/stopwords/'
doc_vec: '../docs/DocVec/'
doc_tfidf: '../docs/DocTfidf/'
doc_vec_train: '../docs/DocVec_train/'
doc_tfidf_train: '../docs/DocTfidf_train/'
doc_vec_validation: '../docs/DocVec_validation/'
doc_tfidf_validation: '../docs/DocTfidf_validation/'
doc_vec_kernel: '../docs/DocVec_kernel/'
doc_tfidf_kernel: '../docs/DocTfidf_kernel/'
navie_bayes_model_by_industry_dir_road: '../docs/navie_bayes_model/一级行业/'
navie_bayes_model_by_kind_dir_road: '../docs/navie_bayes_model/稿件类型/'
navie_bayes_model_tfidf_by_industry_dir_road: '../docs/navie_bayes_model_tfidf/一级行业/'
navie_bayes_model_tfidf_by_kind_dir_road: '../docs/navie_bayes_model_tfidf/稿件类型/'
svm_model_by_industry_dir_road: '../docs/svm_model/一级行业/'
svm_model_by_kind_dir_road: '../docs/svm_model/稿件类型/'
svm_model_tfidf_by_industry_dir_road: '../docs/svm_model_tfidf/一级行业/'
svm_model_tfidf_by_kind_dir_road: '../docs/svm_model_tfidf/稿件类型/'
predict_result_road_vec: '../docs/predict_result/vec/'
predict_result_road_tfidf: '../docs/predict_result/tfidf/'

